title: "EmbedLinuxAcademy"
description: "C, C++, Embedded Linux, Yocto build, kernel driver tutorials"
baseurl: "" # leave this blank for GitHub Pages root
url: "https://embeddlinux.github.io" # your GitHub Pages URL
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: kramdown
